#!/bin/bash
  #####  #####     ##     ####   #    #  #    #    ##    #    #
    #    #    #   #  #   #    #  #   #   ##  ##   #  #   ##   #
    #    #    #  #    #  #       ####    # ## #  #    #  # #  #
    #    #####   ######  #       #  #    #    #  ######  #  # #
    #    #   #   #    #  #    #  #   #   #    #  #    #  #   ##
    #    #    #  #    #   ####   #    #  #    #  #    #  #    #

source trackman.conf
rm $WINID 2>/dev/null
while [ 0 ]
do
    window_id=`xprop -root | grep '_NET_ACTIVE_WINDOW(WINDOW)'| cut -d '#' -f 2`
    window=`xprop -id $window_id| grep 'WM_NAME(STRING)'| cut -d '"' -f 2`
    application=`xprop -id $window_id| grep 'WM_CLASS(STRING)'| cut -d '"' -f 4`
    old_window=`cat $WINID 2>/dev/null`
    if [ "$old_window" != "$window" ]
    then
        echo $window > $WINID
        echo `date`
        echo $window_id' '$application': '$window
    fi
    sleep 5
done
