#!/bin/bash

  #####  #####     ##     ####   #    #  #    #    ##    #    #
    #    #    #   #  #   #    #  #   #   ##  ##   #  #   ##   #
    #    #    #  #    #  #       ####    # ## #  #    #  # #  #
    #    #####   ######  #       #  #    #    #  ######  #  # #
    #    #   #   #    #  #    #  #   #   #    #  #    #  #   ##
    #    #    #  #    #   ####   #    #  #    #  #    #  #    #

if [ $# -eq 0 ]
then
    port=1050
else
    port=$1
fi
echo "starting trackman-server..."
while [ 0 ]
do
    ./server $port
done
