#!/bin/bash

  #####  #####     ##     ####   #    #  #    #    ##    #    #
    #    #    #   #  #   #    #  #   #   ##  ##   #  #   ##   #
    #    #    #  #    #  #       ####    # ## #  #    #  # #  #
    #    #####   ######  #       #  #    #    #  ######  #  # #
    #    #   #   #    #  #    #  #   #   #    #  #    #  #   ##
    #    #    #  #    #   ####   #    #  #    #  #    #  #    #

source trackman.conf

if [ $# -eq 0 ]
then
    server_ip='localhost'
else
    server_ip=$1
fi

if [ $# -ge 2 ]
then
    port=$2
else
    port=1050
fi

silent=1;
for i in $*; do if [ "$i" = "--silent" ]; then silent=0; fi; done

if [ $silent -eq 1 ]; then echo "starting to capture...."; fi
./capture&
if [ $silent -eq 1 ] && [ $? -eq 0 ]; then
    echo "starting trackman-client.."
elif [ $silent -eq 1 ]; then
    echo "ERROR failed to capture.. Try again"
    exit 1
fi

while [ 0 ]
do
    data=`sed -n '1p' $DUMP_FILE`
    if [ "$data" != "" ]; then
        if [ $silent -eq 1 ]; then
            ./client $server_ip $port "$data" 2>/dev/null
        else
            ./client $server_ip $port "$data" >/dev/null 2>/dev/null
        fi
        if [ $? -eq 0 ]; then
            sed -n '2,$p' $DUMP_FILE > temp_dump
            cat temp_dump >$DUMP_FILE
            rm temp_dump
        fi
    fi
done
